Now test script will stop at failure and fixed divide tests.

diff --git a/tests/tests b/tests/tests
--- a/tests/tests
+++ b/tests/tests
@@ -1,17 +1,15 @@
 #!/bin/env bash
 
-export YIPPY_EXE=${YIPPY_DIR}/yippy
+set -e
 
-count_ok=0
-count_fail=0
+export YIPPY_EXE=${YIPPY_DIR}/yippy
 
 if_ok() {
 	if [[ $1 -eq $2 ]]; then
 		echo -e "Test:OK\n"
-		let "count_ok++"
 	else
-		echo -e "Test:Fail\n"
-		let "count_fail++"
+		echo -e "Test:Failed\n"
+		exit 1
 	fi
 
 }
@@ -23,6 +21,3 @@ echo "*************TEST****************"
 for file in *.sh; do
 	./${file}
 done
-
-echo "${count_ok} test Passed."
-echo "${count_fail} test Failed."
